// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THweb.data;

#nullable disable

namespace THweb.Migrations
{
    [DbContext(typeof(CoffeShopDbcontext))]
    partial class CoffeShopDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("THweb.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("istrendingproduct")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Detail = "Name product",
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee-1024x536.webp",
                            Name = "America",
                            Price = 25m,
                            istrendingproduct = false
                        },
                        new
                        {
                            ID = 2,
                            Detail = "Vietnamese product",
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee-1024x536.webp",
                            Name = "Vietnam",
                            Price = 20m,
                            istrendingproduct = false
                        },
                        new
                        {
                            ID = 3,
                            Detail = "UK product",
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee-1024x536.webp",
                            Name = "United Kingdom",
                            Price = 15m,
                            istrendingproduct = false
                        },
                        new
                        {
                            ID = 4,
                            Detail = "India product",
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee-1024x536.webp",
                            Name = "India",
                            Price = 15m,
                            istrendingproduct = false
                        },
                        new
                        {
                            ID = 5,
                            Detail = "Russian product",
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee-1024x536.webp",
                            Name = "Russian",
                            Price = 25m,
                            istrendingproduct = false
                        },
                        new
                        {
                            ID = 6,
                            Detail = "France product",
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee-1024x536.webp",
                            Name = "France",
                            Price = 35m,
                            istrendingproduct = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
